export interface Tool {
  id: string;
  name: string;
  description: string;
  category: "Calculators" | "Converters" | "Generators" | "Validators" | "Developer" | "Text" | "Image" | "SEO" | "Networking" | "Math";
  icon: string;
  path: string;
  popular: boolean;
}

export const tools: Tool[] = [
  // CALCULATORS (20)
  { id: "sip-calculator", name: "SIP Calculator", description: "Calculate potential returns on your SIP investments.", category: "Calculators", icon: "TrendingUp", path: "/calculators/sip", popular: true },
  { id: "emi-calculator", name: "EMI Calculator", description: "Calculate monthly loan repayments.", category: "Calculators", icon: "Calculator", path: "/calculators/emi", popular: true },
  { id: "compound-interest", name: "Compound Interest", description: "Visualize long-term wealth growth.", category: "Calculators", icon: "Coins", path: "/calculators/compound-interest", popular: true },
  { id: "bmi-calculator", name: "BMI Calculator", description: "Calculate Body Mass Index and health status.", category: "Math", icon: "Activity", path: "/math-tools/bmi-calculator", popular: false },
  { id: "age-calculator", name: "Age Calculator", description: "Precise age and milestone calculation.", category: "Math", icon: "Calendar", path: "/math-tools/age-calculator", popular: false },
  { id: "mortgage-calculator", name: "Mortgage Calculator", description: "Estimate monthly home loan payments.", category: "Calculators", icon: "Home", path: "/calculators/mortgage", popular: true },
  { id: "salary-calculator", name: "Salary Calculator", description: "Convert between periodic pay rates.", category: "Calculators", icon: "Wallet", path: "/calculators/salary", popular: true },
  { id: "tax-calculator", name: "Tax Calculator", description: "Estimate income tax based on brackets.", category: "Calculators", icon: "Receipt", path: "/calculators/tax", popular: false },
  { id: "investment-return", name: "Investment Return", description: "Calculate ROI and CAGR.", category: "Calculators", icon: "BarChart", path: "/calculators/investment-return", popular: true },
  { id: "loan-calculator", name: "Loan Calculator", description: "Advanced loan amortization and charts.", category: "Math", icon: "CreditCard", path: "/math-tools/loan-calculator", popular: false },
  { id: "percentage-calculator", name: "Percentage Calculator", description: "Growth, decrease, and ratio math.", category: "Math", icon: "Percent", path: "/math-tools/percentage-calculator", popular: true },
  { id: "gpa-calculator", name: "GPA Calculator", description: "Calculate academic performance scores.", category: "Math", icon: "GraduationCap", path: "/math-tools/gpa-calculator", popular: false },
  { id: "retirement-planner", name: "Retirement Planner", description: "Plan your future savings goal.", category: "Calculators", icon: "Palmtree", path: "/calculators/retirement", popular: true },
  { id: "savings-goal", name: "Savings Goal", description: "Target-based saving strategy.", category: "Calculators", icon: "PiggyBank", path: "/calculators/savings-goal", popular: false },
  { id: "vat-calculator", name: "VAT Calculator", description: "Add/remove Value Added Tax.", category: "Calculators", icon: "ShieldCheck", path: "/calculators/vat", popular: false },
  { id: "gst-calculator", name: "GST Calculator", description: "Goods and Services Tax calculation.", category: "Calculators", icon: "FileText", path: "/calculators/gst", popular: false },
  { id: "inflation-calc", name: "Inflation Calculator", description: "Purchasing power analysis.", category: "Calculators", icon: "ArrowUpRight", path: "/calculators/inflation", popular: false },
  { id: "discount-calc", name: "Discount Calculator", description: "Final price after multi-discounts.", category: "Calculators", icon: "Tag", path: "/calculators/discount", popular: false },
  { id: "date-difference", name: "Date Difference", description: "Calculate delta between two dates.", category: "Calculators", icon: "Clock", path: "/calculators/date-diff", popular: false },
  { id: "fuel-cost", name: "Fuel Cost Calculator", description: "Trip cost estimation.", category: "Calculators", icon: "Fuel", path: "/calculators/fuel-cost", popular: false },

  // CONVERTERS (20)
  { id: "unit-converter", name: "Unit Converter", description: "Universal unit scaling (Length, Mass, Data).", category: "Math", icon: "Ruler", path: "/math-tools/unit-converter", popular: true },
  { id: "currency-converter", name: "Currency Converter", description: "Real-time global exchange rates.", category: "Converters", icon: "Globe", path: "/converters/currency", popular: true },
  { id: "json-yaml", name: "JSON to YAML", description: "Bi-directional config transformation.", category: "Converters", icon: "Settings", path: "/converters/json-yaml", popular: true },
  { id: "base64-image", name: "Base64 to Image", description: "Decode Base64 strings to images.", category: "Converters", icon: "Image", path: "/converters/base64-image", popular: true },
  { id: "ascii-text", name: "ASCII to Text", description: "Convert between ASCII and Text.", category: "Converters", icon: "Type", path: "/converters/ascii-text", popular: false },
  { id: "markdown-to-html", name: "Markdown to HTML", description: "Render Markdown as valid HTML.", category: "Converters", icon: "FileCode", path: "/converters/markdown-html", popular: false },
  { id: "xml-json", name: "XML to JSON", description: "Parse XML into JSON format.", category: "Converters", icon: "Terminal", path: "/converters/xml-json", popular: false },
  { id: "rgb-to-hex", name: "RGB to HEX", description: "Professional color code conversion.", category: "Converters", icon: "Palette", path: "/converters/colors", popular: true },
  { id: "json-to-csv", name: "JSON to CSV", description: "Convert JSON to flat CSV files.", category: "Converters", icon: "Table", path: "/converters/json-csv", popular: true },
  { id: "csv-to-json", name: "CSV to JSON", description: "Convert CSV to structured JSON.", category: "Converters", icon: "FileJson", path: "/converters/csv-json", popular: false },
  { id: "binary-converter", name: "Binary Converter", description: "Dec, Bin, Oct, Hex conversion.", category: "Converters", icon: "Hash", path: "/converters/binary", popular: false },
  { id: "unix-timestamp", name: "Unix Timestamp", description: "Human dates to Unix time.", category: "Converters", icon: "Timer", path: "/converters/unix-time", popular: true },
  { id: "temperature-conv", name: "Temperature Conv", description: "Celsius, Fahrenheit, Kelvin.", category: "Converters", icon: "Thermometer", path: "/converters/temperature", popular: false },
  { id: "data-size-conv", name: "Data Size Conv", description: "Bytes to GB/TB conversion.", category: "Converters", icon: "Database", path: "/converters/data-size", popular: false },
  { id: "area-converter", name: "Area Converter", description: "Land and surface measurement.", category: "Converters", icon: "Box", path: "/converters/area", popular: false },
  { id: "speed-converter", name: "Speed Converter", description: "KMH, MPH, Knots conversion.", category: "Converters", icon: "Zap", path: "/converters/speed", popular: false },
  { id: "morse-code", name: "Morse Code", description: "Text to Morse translation.", category: "Converters", icon: "Waves", path: "/converters/morse", popular: false },
  { id: "roman-numerals", name: "Roman Numerals", description: "Integer to Roman conversion.", category: "Converters", icon: "Columns", path: "/converters/roman", popular: false },
  { id: "svg-to-png", name: "SVG to PNG", description: "Vector to raster conversion.", category: "Converters", icon: "FileImage", path: "/converters/svg-png", popular: false },
  { id: "weight-converter", name: "Weight Converter", description: "Mass and weight scaling.", category: "Converters", icon: "Scale", path: "/converters/weight", popular: false },
  { id: "file-converter", name: "File Converter", description: "Universal document format changer.", category: "Converters", icon: "FileText", path: "/converters/file-converter", popular: true },
  { id: "json-to-excel", name: "JSON to Excel", description: "Convert JSON to XLSX spreadsheets.", category: "Converters", icon: "Table", path: "/converters/json-excel", popular: false },

  // GENERATORS (20)
  { id: "password-generator", name: "Password Gen", description: "Secure, random password creator.", category: "Generators", icon: "Lock", path: "/generators/password-generator", popular: true },
  { id: "lorem-ipsum", name: "Lorem Ipsum", description: "Professional placeholder text.", category: "Generators", icon: "AlignLeft", path: "/generators/lorem-ipsum", popular: true },
  { id: "uuid", name: "UUID Generator", description: "Bulk UUID v1/v4 generation.", category: "Generators", icon: "Fingerprint", path: "/generators/uuid", popular: true },
  { id: "qr-code", name: "QR Code Gen", description: "High-quality QR code creator.", category: "Generators", icon: "QrCode", path: "/generators/qr-code", popular: true },
  { id: "hash", name: "Hash Generator", description: "SHA256, MD5 hash creator.", category: "Generators", icon: "Key", path: "/generators/hash", popular: true },
  { id: "dummy-image", name: "Dummy Image", description: "Placeholder image generator.", category: "Generators", icon: "PictureInPicture", path: "/generators/dummy-image", popular: false },
  { id: "sql", name: "SQL Generator", description: "Dummy data SQL statements.", category: "Generators", icon: "DatabaseBackup", path: "/generators/sql", popular: false },
  { id: "regex", name: "RegEx Generator", description: "Interactive pattern builder.", category: "Generators", icon: "Parentheses", path: "/generators/regex", popular: true },
  { id: "hashtag-generator", name: "Hashtag Generator", description: "Social media tag discovery.", category: "Generators", icon: "Hash", path: "/generators/hashtag-generator", popular: true },
  { id: "username-generator", name: "Username Gen", description: "Creative name suggestions.", category: "Generators", icon: "User", path: "/generators/username-generator", popular: false },
  { id: "paragraph-generator", name: "Paragraph Gen", description: "Structured placeholder text.", category: "Generators", icon: "AlignLeft", path: "/generators/paragraph-generator", popular: false },
  { id: "api-key-gen", name: "API Key Gen", description: "Unique application keys.", category: "Generators", icon: "Shield", path: "/generators/api-key", popular: false },
  { id: "gradient-gen", name: "Gradient Gen", description: "CSS gradient design tool.", category: "Generators", icon: "Wind", path: "/generators/gradients", popular: false },
  { id: "json-mock-data", name: "Mock Data Gen", description: "Realistic JSON test data.", category: "Generators", icon: "Braces", path: "/generators/json-data", popular: true },
  { id: "credit-card", name: "CC Generator", description: "Test card numbers (Luhn).", category: "Generators", icon: "CreditCard", path: "/generators/credit-card", popular: false },
  { id: "barcode", name: "Barcode Gen", description: "EAN, UPC barcode creator.", category: "Generators", icon: "Barcode", path: "/generators/barcode", popular: false },
  { id: "user-agent", name: "User Agent Gen", description: "Browser string generation.", category: "Generators", icon: "MousePointer2", path: "/generators/user-agent", popular: false },
  { id: "jwt-gen", name: "JWT Generator", description: "Auth token creation.", category: "Generators", icon: "LockKeyhole", path: "/generators/jwt", popular: false },
  { id: "htaccess", name: "HTAccess Gen", description: "Apache rule generation.", category: "Generators", icon: "Server", path: "/generators/htaccess", popular: false },
  { id: "ssh-key", name: "SSH Key Gen", description: "RSA/Ed25519 pair generation.", category: "Generators", icon: "KeySquare", path: "/generators/ssh-key", popular: false },

  // TEXT & SEO (20)
  { id: "word-counter", name: "Word Counter", description: "Detailed text metrics and stats.", category: "Text", icon: "FileText", path: "/text-tools/word-counter", popular: true },
  { id: "case-converter", name: "Case Converter", description: "Camel, Snake, Pascal conversion.", category: "Text", icon: "Type", path: "/text-tools/case-converter", popular: false },
  { id: "slug-generator", name: "Slug Generator", description: "SEO-friendly URL creation.", category: "Text", icon: "Link2", path: "/text-tools/slug-generator", popular: false },
  { id: "remove-duplicates", name: "Remove Duplicates", description: "Clean duplicate lines instantly.", category: "Text", icon: "ListFilter", path: "/text-tools/remove-duplicate-lines", popular: false },
  { id: "text-reverser", name: "Text Reverser", description: "Flip characters or words.", category: "Text", icon: "RotateCcw", path: "/text-tools/text-reverser", popular: false },
  { id: "whitespace-remover", name: "Space Remover", description: "Clean extra whitespace.", category: "Text", icon: "Eraser", path: "/text-tools/whitespace-remover", popular: false },
  { id: "bionic-reading", name: "Bionic Reading", description: "Enhance reading speed/focus.", category: "Text", icon: "Zap", path: "/text-tools/bionic-reading", popular: true },
  { id: "keyword-density", name: "Keyword Density Checker", description: "SEO content frequency and optimization check.", category: "Validators", icon: "Search", path: "/seo-tools/keyword-density", popular: true },
  { id: "meta-tag-generator", name: "Meta Tag Gen", description: "Social & SEO metadata tags.", category: "SEO", icon: "Globe", path: "/seo-tools/meta-tag-generator", popular: true },
  { id: "robots-txt-generator", name: "Robots.txt Gen", description: "Crawl management rules.", category: "SEO", icon: "Bot", path: "/seo-tools/robots-txt-generator", popular: false },
  { id: "sitemap-generator", name: "Sitemap Gen", description: "XML sitemap architecture.", category: "SEO", icon: "Map", path: "/seo-tools/sitemap-generator", popular: false },
  { id: "hreflang-generator", name: "Hreflang Gen", description: "International SEO tags.", category: "SEO", icon: "Languages", path: "/seo-tools/hreflang-generator", popular: false },
  { id: "content-ideas", name: "Content Ideas", description: "Viral blog topic generation.", category: "SEO", icon: "Lightbulb", path: "/seo-tools/content-ideas", popular: true },
  { id: "character-counter", name: "Char Counter", description: "Precise character metrics.", category: "Text", icon: "Type", path: "/text-tools/character-counter", popular: false },
  { id: "random-text-gen", name: "Random Text", description: "Test sentence generation.", category: "Text", icon: "MessageSquare", path: "/text-tools/random-text-generator", popular: false },
  { id: "html-entities-gen", name: "Entity Encoder", description: "HTML entity conversion.", category: "Text", icon: "Quote", path: "/converters/html-entities", popular: false },
  { id: "lorem-paragraph", name: "Lorem Para", description: "Paragraph-specific lorem.", category: "Text", icon: "AlignJustify", path: "/generators/paragraph-generator", popular: false },
  { id: "hashtag-discover", name: "Hash Discover", description: "Tag discovery for social.", category: "Text", icon: "Hash", path: "/generators/hashtag-generator", popular: false },
  { id: "username-ideator", name: "User Ideator", description: "Name brainstorming tool.", category: "Text", icon: "UserPlus", path: "/generators/username-generator", popular: false },
  { id: "slug-master", name: "Slug Master", description: "Advanced URL slugging.", category: "Text", icon: "Link", path: "/text-tools/slug-generator", popular: false },

  // DEVELOPER, IMAGE & NETWORKING (20)
  { id: "json-validator", name: "JSON Validator", description: "Validate and format JSON code with precision.", category: "Validators", icon: "ShieldCheck", path: "/developer-tools/json-validator", popular: true },
  { id: "sql-formatter", name: "SQL Formatter", description: "Beautify complex SQL queries.", category: "Developer", icon: "Database", path: "/developer-tools/sql-formatter", popular: true },
  { id: "css-formatter", name: "CSS Formatter", description: "Optimize and beautify CSS.", category: "Developer", icon: "Paintbrush", path: "/developer-tools/css-formatter", popular: false },
  { id: "diff-checker", name: "Diff Checker", description: "Compare text or code changes for discrepancies.", category: "Validators", icon: "ArrowLeftRight", path: "/developer-tools/diff-checker", popular: true },
  { id: "jwt-debugger", name: "JWT Validator", description: "Decode and verify JWT tokens and signatures.", category: "Validators", icon: "ShieldAlert", path: "/developer-tools/jwt-debugger", popular: true },
  { id: "cron-parser", name: "Cron Parser", description: "Explain cron expressions.", category: "Developer", icon: "CalendarCheck", path: "/developer-tools/cron-parser", popular: false },
  { id: "ua-parser", name: "UA Parser", description: "Deep device/browser insights.", category: "Developer", icon: "Monitor", path: "/developer-tools/ua-parser", popular: false },
  { id: "ip-lookup", name: "IP Lookup", description: "Real-time geolocation & ASN.", category: "Networking", icon: "MapPin", path: "/networking-tools/ip-lookup", popular: true },
  { id: "http-headers", name: "HTTP Headers", description: "Audit server response headers.", category: "Networking", icon: "Activity", path: "/networking-tools/http-headers", popular: false },
  { id: "image-cropper", name: "Image Cropper", description: "Professional-grade editing.", category: "Image", icon: "Crop", path: "/image-tools/image-cropper", popular: true },
  { id: "image-resizer", name: "Image Resizer", description: "Scale images with precision.", category: "Image", icon: "Maximize", path: "/image-tools/image-resizer", popular: true },
  { id: "image-compressor", name: "Image Compressor", description: "Optimize images to desired size.", category: "Image", icon: "Zap", path: "/image-tools/image-compressor", popular: true },
  { id: "color-extractor", name: "Color Extractor", description: "Extract palette from images.", category: "Image", icon: "Pipette", path: "/image-tools/color-extractor", popular: true },
  { id: "prime-checker", name: "Prime Checker", description: "Validate number primality with high speed.", category: "Validators", icon: "Zap", path: "/math-tools/prime-checker", popular: false },
  { id: "prime-factorization", name: "Prime Factors", description: "Integer decomposition tool.", category: "Math", icon: "Box", path: "/math-tools/prime-factorization", popular: false },
  { id: "equation-solver", name: "Equation Solver", description: "Linear & Quadratic algebra.", category: "Math", icon: "Settings2", path: "/math-tools/equation-solver", popular: false },
  { id: "random-number-gen", name: "Random Num Gen", description: "Secure bulk randomization.", category: "Math", icon: "Dices", path: "/math-tools/random-number-generator", popular: true },
  { id: "statistics-calculator", name: "Stats Calculator", description: "Mean, Median, Std Dev.", category: "Math", icon: "BarChart3", path: "/math-tools/statistics-calculator", popular: false },
  { id: "base64-converter", name: "Base64 Master", description: "String & File conversion.", category: "Developer", icon: "Code", path: "/developer-tools/base64-converter", popular: false },
  { id: "url-converter", name: "URL Master", description: "Encode/Decode URL params.", category: "Developer", icon: "Globe", path: "/developer-tools/url-converter", popular: false },
  { id: "json-mock-master", name: "JSON Master", description: "Advanced mock generation.", category: "Developer", icon: "FileJson", path: "/generators/json-data", popular: false },
];
