export interface Tool {
  id: string;
  name: string;
  description: string;
  category: "Calculators" | "Converters" | "Generators" | "Validators";
  icon: string;
  path: string;
  popular: boolean;
}

export const tools: Tool[] = [
  // CALCULATORS (25)
  {
    id: "sip-calculator",
    name: "SIP Calculator",
    description: "Calculate potential returns on your Systematic Investment Plan investments.",
    category: "Calculators",
    icon: "TrendingUp",
    path: "/calculators/sip",
    popular: true,
  },
  {
    id: "emi-calculator",
    name: "EMI Calculator",
    description: "Calculate monthly loan repayments for home, car, or personal loans.",
    category: "Calculators",
    icon: "Calculator",
    path: "/calculators/emi",
    popular: true,
  },
  {
    id: "compound-interest",
    name: "Compound Interest",
    description: "Visualize how your wealth grows over time with compound interest.",
    category: "Calculators",
    icon: "Coins",
    path: "/calculators/compound-interest",
    popular: true,
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index and health category.",
    category: "Calculators",
    icon: "Activity",
    path: "/calculators/bmi",
    popular: false,
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    description: "Determine your exact age in years, months, days, and hours.",
    category: "Calculators",
    icon: "Calendar",
    path: "/calculators/age",
    popular: false,
  },
  {
    id: "mortgage-calculator",
    name: "Mortgage Calculator",
    description: "Estimate your monthly mortgage payments including taxes and insurance.",
    category: "Calculators",
    icon: "Home",
    path: "/calculators/mortgage",
    popular: true,
  },
  {
    id: "tip-calculator",
    name: "Tip Calculator",
    description: "Quickly calculate tips and split bills among friends.",
    category: "Calculators",
    icon: "DollarSign",
    path: "/calculators/tip",
    popular: false,
  },
  {
    id: "salary-calculator",
    name: "Salary Calculator",
    description: "Convert between hourly, weekly, monthly, and annual pay.",
    category: "Calculators",
    icon: "Wallet",
    path: "/calculators/salary",
    popular: true,
  },
  {
    id: "tax-calculator",
    name: "Tax Calculator",
    description: "Estimate your income tax based on current tax brackets.",
    category: "Calculators",
    icon: "Receipt",
    path: "/calculators/tax",
    popular: false,
  },
  {
    id: "investment-return",
    name: "Investment Return",
    description: "Calculate the ROI and CAGR for any investment.",
    category: "Calculators",
    icon: "BarChart",
    path: "/calculators/investment-return",
    popular: true,
  },
  {
    id: "fuel-cost",
    name: "Fuel Cost Calculator",
    description: "Estimate the fuel cost and quantity for your next road trip.",
    category: "Calculators",
    icon: "Fuel",
    path: "/calculators/fuel-cost",
    popular: false,
  },
  {
    id: "percentage-calc",
    name: "Percentage Calculator",
    description: "Calculate percentage increases, decreases, and common ratios.",
    category: "Calculators",
    icon: "Percent",
    path: "/calculators/percentage",
    popular: true,
  },
  {
    id: "loan-affordability",
    name: "Loan Affordability",
    description: "Check how much loan you can afford based on your income.",
    category: "Calculators",
    icon: "Briefcase",
    path: "/calculators/loan-affordability",
    popular: false,
  },
  {
    id: "retirement-planner",
    name: "Retirement Planner",
    description: "Calculate how much you need to save to retire comfortably.",
    category: "Calculators",
    icon: "Palmtree",
    path: "/calculators/retirement",
    popular: true,
  },
  {
    id: "savings-goal",
    name: "Savings Goal",
    description: "Find out how much to save monthly to reach your target.",
    category: "Calculators",
    icon: "PiggyBank",
    path: "/calculators/savings-goal",
    popular: false,
  },
  {
    id: "vat-calculator",
    name: "VAT Calculator",
    description: "Add or remove Value Added Tax from any amount.",
    category: "Calculators",
    icon: "ShieldCheck",
    path: "/calculators/vat",
    popular: false,
  },
  {
    id: "gst-calculator",
    name: "GST Calculator",
    description: "Calculate Goods and Services Tax for Indian financial contexts.",
    category: "Calculators",
    icon: "FileText",
    path: "/calculators/gst",
    popular: false,
  },
  {
    id: "inflation-calc",
    name: "Inflation Calculator",
    description: "See how inflation affects the purchasing power of your money.",
    category: "Calculators",
    icon: "ArrowUpRight",
    path: "/calculators/inflation",
    popular: false,
  },
  {
    id: "discount-calc",
    name: "Discount Calculator",
    description: "Quickly find the final price after applying multiple discounts.",
    category: "Calculators",
    icon: "Tag",
    path: "/calculators/discount",
    popular: false,
  },
  {
    id: "date-difference",
    name: "Date Difference",
    description: "Calculate the number of days, weeks, or months between dates.",
    category: "Calculators",
    icon: "Clock",
    path: "/calculators/date-diff",
    popular: false,
  },
  {
    id: "binary-calc",
    name: "Binary Calculator",
    description: "Perform arithmetic operations on binary numbers.",
    category: "Calculators",
    icon: "Binary",
    path: "/calculators/binary-math",
    popular: false,
  },
  {
    id: "scientific-calc",
    name: "Scientific Calculator",
    description: "Advanced mathematical functions for complex equations.",
    category: "Calculators",
    icon: "Cpu",
    path: "/calculators/scientific",
    popular: false,
  },
  {
    id: "grade-calc",
    name: "Grade Calculator",
    description: "Calculate your final grade or GPA based on weighted scores.",
    category: "Calculators",
    icon: "GraduationCap",
    path: "/calculators/grade",
    popular: false,
  },
  {
    id: "calories-burned",
    name: "Calories Burned",
    description: "Estimate calories burned during various physical activities.",
    category: "Calculators",
    icon: "Flame",
    path: "/calculators/calories",
    popular: false,
  },
  {
    id: "unit-price-calc",
    name: "Unit Price Calc",
    description: "Compare products to find the best value for your money.",
    category: "Calculators",
    icon: "ShoppingCart",
    path: "/calculators/unit-price",
    popular: false,
  },

  // CONVERTERS (25)
  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert between metric and imperial units for length, mass, etc.",
    category: "Converters",
    icon: "Ruler",
    path: "/converters/units",
    popular: true,
  },
  {
    id: "currency-converter",
    name: "Currency Converter",
    description: "Real-time exchange rates for global currencies.",
    category: "Converters",
    icon: "Globe",
    path: "/converters/currency",
    popular: true,
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV",
    description: "Convert complex JSON structures into clean CSV files.",
    category: "Converters",
    icon: "Table",
    path: "/converters/json-csv",
    popular: true,
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder",
    description: "Encode or decode strings and files to/from Base64.",
    category: "Converters",
    icon: "Code",
    path: "/developer-tools/base64-converter",
    popular: true,
  },
  {
    id: "rgb-to-hex",
    name: "RGB to HEX",
    description: "Convert color codes between RGB, HEX, HSL, and CMYK.",
    category: "Converters",
    icon: "Palette",
    path: "/converters/colors",
    popular: true,
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Change text case to camelCase, snake_case, PascalCase, etc.",
    category: "Converters",
    icon: "Type",
    path: "/text-tools/case-converter",
    popular: false,
  },
  {
    id: "unix-timestamp",
    name: "Unix Timestamp",
    description: "Convert Unix timestamps to human-readable dates and vice versa.",
    category: "Converters",
    icon: "Timer",
    path: "/converters/unix-time",
    popular: true,
  },
  {
    id: "binary-converter",
    name: "Binary Converter",
    description: "Convert between decimal, binary, octal, and hexadecimal.",
    category: "Converters",
    icon: "Hash",
    path: "/converters/binary",
    popular: false,
  },
  {
    id: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Instantly render Markdown text as valid HTML code.",
    category: "Converters",
    icon: "FileCode",
    path: "/converters/markdown-html",
    popular: false,
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON",
    description: "Transform structured CSV data into JSON format.",
    category: "Converters",
    icon: "FileJson",
    path: "/converters/csv-json",
    popular: false,
  },
  {
    id: "temperature-conv",
    name: "Temperature Conv",
    description: "Convert between Celsius, Fahrenheit, and Kelvin.",
    category: "Converters",
    icon: "Thermometer",
    path: "/converters/temperature",
    popular: false,
  },
  {
    id: "data-size-conv",
    name: "Data Size Conv",
    description: "Convert between Bytes, KB, MB, GB, TB, and more.",
    category: "Converters",
    icon: "Database",
    path: "/converters/data-size",
    popular: false,
  },
  {
    id: "area-converter",
    name: "Area Converter",
    description: "Convert between square meters, acres, hectares, and more.",
    category: "Converters",
    icon: "Box",
    path: "/converters/area",
    popular: false,
  },
  {
    id: "speed-converter",
    name: "Speed Converter",
    description: "Convert between km/h, mph, knots, and m/s.",
    category: "Converters",
    icon: "Zap",
    path: "/converters/speed",
    popular: false,
  },
  {
    id: "yaml-to-json",
    name: "YAML to JSON",
    description: "Switch between YAML and JSON configurations easily.",
    category: "Converters",
    icon: "Settings",
    path: "/converters/yaml-json",
    popular: false,
  },
  {
    id: "html-entities",
    name: "HTML Entities",
    description: "Encode or decode HTML entities in your strings.",
    category: "Converters",
    icon: "Quote",
    path: "/converters/html-entities",
    popular: false,
  },
  {
    id: "url-encoder",
    name: "URL Encoder",
    description: "Safely encode and decode URL parameters.",
    category: "Converters",
    icon: "Globe",
    path: "/developer-tools/url-converter",
    popular: true,
  },
  {
    id: "xml-to-json",
    name: "XML to JSON",
    description: "Parse legacy XML data into modern JSON format.",
    category: "Converters",
    icon: "Terminal",
    path: "/converters/xml-json",
    popular: false,
  },
  {
    id: "morse-code",
    name: "Morse Code",
    description: "Translate text to Morse code and back again.",
    category: "Converters",
    icon: "Waves",
    path: "/converters/morse",
    popular: false,
  },
  {
    id: "roman-numerals",
    name: "Roman Numerals",
    description: "Convert integers to Roman numerals and vice versa.",
    category: "Converters",
    icon: "Columns",
    path: "/converters/roman",
    popular: false,
  },
  {
    id: "image-to-webp",
    name: "Image to WebP",
    description: "Optimize your images by converting them to WebP format.",
    category: "Converters",
    icon: "Image",
    path: "/converters/image-webp",
    popular: false,
  },
  {
    id: "svg-to-png",
    name: "SVG to PNG",
    description: "Convert vector SVG graphics to raster PNG images.",
    category: "Converters",
    icon: "FileImage",
    path: "/converters/svg-png",
    popular: false,
  },
  {
    id: "weight-converter",
    name: "Weight Converter",
    description: "Convert between kilograms, pounds, ounces, and grams.",
    category: "Converters",
    icon: "Scale",
    path: "/converters/weight",
    popular: false,
  },
  {
    id: "time-zone-conv",
    name: "Time Zone Conv",
    description: "Find the time in any city around the world.",
    category: "Converters",
    icon: "Languages",
    path: "/converters/timezones",
    popular: false,
  },
  {
    id: "angle-converter",
    name: "Angle Converter",
    description: "Convert between degrees, radians, and gradians.",
    category: "Converters",
    icon: "Maximize",
    path: "/converters/angle",
    popular: false,
  },

  // GENERATORS (25)
  {
    id: "password-gen",
    name: "Password Gen",
    description: "Create secure, random passwords with custom requirements.",
    category: "Generators",
    icon: "Lock",
    path: "/generators/password-generator",
    popular: true,
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    description: "Generate placeholder text for layouts and designs.",
    category: "Generators",
    icon: "AlignLeft",
    path: "/generators/lorem-ipsum",
    popular: true,
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate bulk UUIDs (v1, v4) for your database or API.",
    category: "Generators",
    icon: "Fingerprint",
    path: "/generators/uuid",
    popular: true,
  },
  {
    id: "qr-code-gen",
    name: "QR Code Gen",
    description: "Generate high-quality QR codes for URLs, text, or WiFi.",
    category: "Generators",
    icon: "QrCode",
    path: "/generators/qr-code",
    popular: true,
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA1, SHA256, and SHA512 hashes.",
    category: "Generators",
    icon: "Key",
    path: "/generators/hash",
    popular: true,
  },
  {
    id: "dummy-image",
    name: "Dummy Image",
    description: "Generate placeholder images with custom dimensions and colors.",
    category: "Generators",
    icon: "PictureInPicture",
    path: "/generators/dummy-image",
    popular: false,
  },
  {
    id: "sql-generator",
    name: "SQL Generator",
    description: "Create dummy SQL INSERT statements for testing databases.",
    category: "Generators",
    icon: "DatabaseBackup",
    path: "/generators/sql",
    popular: false,
  },
  {
    id: "regex-generator",
    name: "RegEx Generator",
    description: "Build complex regular expressions with a simple UI.",
    category: "Generators",
    icon: "Parentheses",
    path: "/generators/regex",
    popular: true,
  },
  {
    id: "sitemap-gen",
    name: "Sitemap Gen",
    description: "Generate XML sitemaps for your website SEO.",
    category: "Generators",
    icon: "Map",
    path: "/generators/sitemap",
    popular: false,
  },
  {
    id: "robots-txt-gen",
    name: "Robots.txt Gen",
    description: "Create a proper robots.txt file for search engine crawlers.",
    category: "Generators",
    icon: "Bot",
    path: "/generators/robots-txt",
    popular: false,
  },
  {
    id: "htaccess-gen",
    name: "HTAccess Gen",
    description: "Generate .htaccess rules for redirects, security, and caching.",
    category: "Generators",
    icon: "Server",
    path: "/generators/htaccess",
    popular: false,
  },
  {
    id: "ssh-key-gen",
    name: "SSH Key Gen",
    description: "Generate secure SSH key pairs (RSA, Ed25519) in your browser.",
    category: "Generators",
    icon: "KeySquare",
    path: "/generators/ssh-key",
    popular: false,
  },
  {
    id: "api-key-gen",
    name: "API Key Gen",
    description: "Create unique API keys for your applications.",
    category: "Generators",
    icon: "Shield",
    path: "/generators/api-key",
    popular: false,
  },
  {
    id: "random-color",
    name: "Random Color",
    description: "Generate harmonious color palettes or random hex codes.",
    category: "Generators",
    icon: "Pipette",
    path: "/generators/colors",
    popular: false,
  },
  {
    id: "strong-name-gen",
    name: "Random Name",
    description: "Generate realistic names for users, pets, or characters.",
    category: "Generators",
    icon: "User",
    path: "/generators/names",
    popular: false,
  },
  {
    id: "string-gen",
    name: "Random String",
    description: "Generate random alphanumeric strings of any length.",
    category: "Generators",
    icon: "Shuffle",
    path: "/generators/string",
    popular: false,
  },
  {
    id: "json-mock-data",
    name: "JSON Mock Data",
    description: "Create realistic mock JSON data for API testing.",
    category: "Generators",
    icon: "Braces",
    path: "/generators/json-data",
    popular: true,
  },
  {
    id: "credit-card-test",
    name: "CC Generator",
    description: "Generate valid credit card numbers for integration testing.",
    category: "Generators",
    icon: "CreditCard",
    path: "/generators/credit-card",
    popular: false,
  },
  {
    id: "barcode-gen",
    name: "Barcode Gen",
    description: "Generate barcodes (EAN-13, UPC, Code 128) for products.",
    category: "Generators",
    icon: "Barcode",
    path: "/generators/barcode",
    popular: false,
  },
  {
    id: "user-agent-gen",
    name: "User Agent Gen",
    description: "Generate common browser user-agent strings for testing.",
    category: "Generators",
    icon: "MousePointer2",
    path: "/generators/user-agent",
    popular: false,
  },
  {
    id: "jwt-generator",
    name: "JWT Generator",
    description: "Create and sign JSON Web Tokens for authentication testing.",
    category: "Generators",
    icon: "LockKeyhole",
    path: "/generators/jwt",
    popular: false,
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    description: "Convert titles into SEO-friendly URL slugs.",
    category: "Generators",
    icon: "Link2",
    path: "/text-tools/slug-generator",
    popular: false,
  },
  {
    id: "placeholder-text",
    name: "Tag Generator",
    description: "Generate common meta tags and OpenGraph tags for SEO.",
    category: "Generators",
    icon: "Tags",
    path: "/generators/meta-tags",
    popular: false,
  },
  {
    id: "social-share-gen",
    name: "Social Share Gen",
    description: "Create social media sharing links with custom parameters.",
    category: "Generators",
    icon: "Share",
    path: "/generators/social-share",
    popular: false,
  },
  {
    id: "gradient-gen",
    name: "Gradient Gen",
    description: "Design beautiful CSS gradients with live preview.",
    category: "Generators",
    icon: "Wind",
    path: "/generators/gradients",
    popular: false,
  },

  // VALIDATORS (25)
  {
    id: "json-validator",
    name: "JSON Validator",
    description: "Validate and format your JSON code with error highlighting.",
    category: "Validators",
    icon: "ShieldCheck",
    path: "/developer-tools/json-validator",
    popular: true,
  },
  {
    id: "email-validator",
    name: "Email Validator",
    description: "Check if an email address is valid and has a valid domain.",
    category: "Validators",
    icon: "MailCheck",
    path: "/validators/email",
    popular: true,
  },
  {
    id: "url-validator",
    name: "URL Validator",
    description: "Validate the structure and accessibility of any URL.",
    category: "Validators",
    icon: "Link",
    path: "/validators/url",
    popular: true,
  },
  {
    id: "cron-validator",
    name: "Cron Validator",
    description: "Validate and explain cron expressions in plain English.",
    category: "Validators",
    icon: "CalendarCheck",
    path: "/validators/cron",
    popular: true,
  },
  {
    id: "password-strength",
    name: "Pass Strength",
    description: "Analyze the entropy and strength of your passwords.",
    category: "Validators",
    icon: "ShieldAlert",
    path: "/validators/password",
    popular: true,
  },
  {
    id: "credit-card-val",
    name: "CC Validator",
    description: "Verify credit card numbers using the Luhn algorithm.",
    category: "Validators",
    icon: "CreditCard",
    path: "/validators/credit-card",
    popular: false,
  },
  {
    id: "yaml-validator",
    name: "YAML Validator",
    description: "Ensure your YAML files follow correct syntax rules.",
    category: "Validators",
    icon: "FileSearch",
    path: "/validators/yaml",
    popular: false,
  },
  {
    id: "html-validator",
    name: "HTML Validator",
    description: "Check for unclosed tags and syntax errors in HTML snippets.",
    category: "Validators",
    icon: "Layout",
    path: "/validators/html",
    popular: false,
  },
  {
    id: "css-validator",
    name: "CSS Validator",
    description: "Validate your CSS and find potential browser compatibility issues.",
    category: "Validators",
    icon: "Paintbrush",
    path: "/validators/css",
    popular: false,
  },
  {
    id: "js-validator",
    name: "JS Validator",
    description: "Lint and validate your JavaScript code for syntax errors.",
    category: "Validators",
    icon: "FileJson",
    path: "/validators/javascript",
    popular: false,
  },
  {
    id: "ip-validator",
    name: "IP Validator",
    description: "Validate IPv4 and IPv6 addresses and identify subnets.",
    category: "Validators",
    icon: "MapPin",
    path: "/validators/ip",
    popular: false,
  },
  {
    id: "jwt-validator",
    name: "JWT Validator",
    description: "Decode and verify the signature and payload of a JWT.",
    category: "Validators",
    icon: "ShieldQuestion",
    path: "/validators/jwt",
    popular: true,
  },
  {
    id: "isbn-validator",
    name: "ISBN Validator",
    description: "Check the validity of ISBN-10 and ISBN-13 book numbers.",
    category: "Validators",
    icon: "BookOpen",
    path: "/validators/isbn",
    popular: false,
  },
  {
    id: "iban-validator",
    name: "IBAN Validator",
    description: "Validate International Bank Account Numbers for accuracy.",
    category: "Validators",
    icon: "Banknote",
    path: "/validators/iban",
    popular: false,
  },
  {
    id: "xml-validator",
    name: "XML Validator",
    description: "Check XML documents for well-formedness and schema compliance.",
    category: "Validators",
    icon: "FileCode",
    path: "/validators/xml",
    popular: false,
  },
  {
    id: "sql-validator",
    name: "SQL Validator",
    description: "Validate SQL queries and highlight potential syntax errors.",
    category: "Validators",
    icon: "Database",
    path: "/validators/sql",
    popular: false,
  },
  {
    id: "markdown-val",
    name: "Markdown Val",
    description: "Ensure your Markdown documents follow consistent formatting.",
    category: "Validators",
    icon: "FileText",
    path: "/validators/markdown",
    popular: false,
  },
  {
    id: "domain-validator",
    name: "Domain Validator",
    description: "Check if a domain name is valid and view its registration status.",
    category: "Validators",
    icon: "Globe2",
    path: "/validators/domain",
    popular: false,
  },
  {
    id: "uuid-validator",
    name: "UUID Validator",
    description: "Verify if a string is a valid UUID and identify its version.",
    category: "Validators",
    icon: "Fingerprint",
    path: "/validators/uuid",
    popular: false,
  },
  {
    id: "color-validator",
    name: "Color Validator",
    description: "Check if a color code is valid across various formats.",
    category: "Validators",
    icon: "Droplets",
    path: "/validators/color",
    popular: false,
  },
  {
    id: "phone-validator",
    name: "Phone Validator",
    description: "Validate international phone numbers and identify carriers.",
    category: "Validators",
    icon: "Phone",
    path: "/validators/phone",
    popular: false,
  },
  {
    id: "postal-code-val",
    name: "Postal Code Val",
    description: "Check the validity of postal codes for various countries.",
    category: "Validators",
    icon: "Navigation",
    path: "/validators/postal-code",
    popular: false,
  },
  {
    id: "mac-address-val",
    name: "MAC Address Val",
    description: "Validate MAC addresses and identify the manufacturer.",
    category: "Validators",
    icon: "Network",
    path: "/validators/mac-address",
    popular: false,
  },
  {
    id: "base64-validator",
    name: "Base64 Validator",
    description: "Check if a string is a valid Base64 encoded value.",
    category: "Validators",
    icon: "Lock",
    path: "/validators/base64",
    popular: false,
  },
  {
    id: "semver-validator",
    name: "SemVer Validator",
    description: "Validate Semantic Versioning strings for software projects.",
    category: "Validators",
    icon: "GitBranch",
    path: "/validators/semver",
    popular: false,
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and estimate reading time for any text.",
    category: "Converters",
    icon: "FileText",
    path: "/text-tools/word-counter",
    popular: true,
  },
  {
    id: "character-counter",
    name: "Character Counter",
    description: "Count characters with and without spaces, including line breaks and special symbols.",
    category: "Converters",
    icon: "Type",
    path: "/text-tools/character-counter",
    popular: false,
  },
  {
    id: "remove-duplicate-lines",
    name: "Remove Duplicates",
    description: "Instantly remove duplicate lines from your text or lists with customizable filters.",
    category: "Converters",
    icon: "ListFilter",
    path: "/text-tools/remove-duplicate-lines",
    popular: false,
  },
  {
    id: "text-reverser",
    name: "Text Reverser",
    description: "Reverse your text characters or flip the word order instantly.",
    category: "Converters",
    icon: "RotateCcw",
    path: "/text-tools/text-reverser",
    popular: false,
  },
  {
    id: "whitespace-remover",
    name: "Whitespace Remover",
    description: "Clean up your text by removing extra spaces, line breaks, or all whitespace instantly.",
    category: "Converters",
    icon: "Eraser",
    path: "/text-tools/whitespace-remover",
    popular: false,
  },
  {
    id: "random-text-generator",
    name: "Random Text Gen",
    description: "Generate random words, sentences, or paragraphs for design mockups and testing.",
    category: "Generators",
    icon: "Type",
    path: "/text-tools/random-text-generator",
    popular: false,
  },
  {
    id: "hashtag-generator",
    name: "Hashtag Generator",
    description: "Generate optimized, platform-specific hashtags for Instagram, TikTok, LinkedIn, and more.",
    category: "Generators",
    icon: "Hash",
    path: "/generators/hashtag-generator",
    popular: true,
  },
  {
    id: "username-generator",
    name: "Username Generator",
    description: "Generate creative, unique, and professional username suggestions based on your name or interests.",
    category: "Generators",
    icon: "User",
    path: "/generators/username-generator",
    popular: false,
  },
  {
    id: "paragraph-generator",
    name: "Paragraph Generator",
    description: "Generate structured, professional-looking placeholder paragraphs for your layouts and design projects.",
    category: "Generators",
    icon: "AlignLeft",
    path: "/generators/paragraph-generator",
    popular: false,
  },
];
