"use client";

import React, { useState, useMemo } from "react";
import { ToolLayout } from "@/components/tool-layout";
import { tools } from "@/lib/tools";
import { 
  Server, 
  ArrowRight, 
  ShieldAlert, 
  Copy, 
  FileCode, 
  RefreshCw,
  Globe,
  Lock
} from "lucide-react";
import { motion } from "framer-motion";

export default function HTAccessGenerator() {
  const tool = tools.find((t) => t.id === "htaccess")!;
  
  const [options, setOptions] = useState({
    forceHttps: true,
    wwwRedirect: "none",
    blockDirectoryListing: true,
    customError404: "/404.html",
    gzipCompression: true
  });

  const generatedConfig = useMemo(() => {
    let config = "# Generated by UtilityLab .htaccess Generator\n\n";

    if (options.forceHttps) {
      config += "RewriteEngine On\nRewriteCond %{HTTPS} off\nRewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]\n\n";
    }

    if (options.blockDirectoryListing) {
      config += "Options -Indexes\n\n";
    }

    if (options.gzipCompression) {
      config += "<IfModule mod_deflate.c>\n  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript\n</IfModule>\n\n";
    }

    if (options.customError404) {
      config += `ErrorDocument 404 ${options.customError404}\n\n`;
    }

    return config;
  }, [options]);

  return (
    <ToolLayout tool={tool}>
      <div className="space-y-12">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          
          {/* Controls */}
          <div className="bg-white dark:bg-gray-900 rounded-[3rem] p-10 border border-gray-100 dark:border-gray-800 shadow-xl space-y-8">
            <div className="space-y-6">
              {[
                { id: "forceHttps", label: "Force HTTPS Redirect", icon: Lock },
                { id: "blockDirectoryListing", label: "Block Directory Listing", icon: ShieldAlert },
                { id: "gzipCompression", label: "Enable GZIP Compression", icon: RefreshCw },
              ].map((opt) => (
                <button
                  key={opt.id}
                  onClick={() => setOptions({ ...options, [opt.id]: !(options as any)[opt.id] })}
                  className={`w-full flex items-center justify-between p-6 rounded-2xl border transition-all ${(options as any)[opt.id] ? 'bg-indigo-50 border-indigo-200 text-indigo-700 dark:bg-indigo-900/30 dark:border-indigo-800' : 'bg-gray-50 border-gray-100 text-gray-500 dark:bg-gray-800 dark:border-gray-700'}`}
                >
                  <div className="flex items-center gap-4">
                    <opt.icon size={20} />
                    <span className="font-bold">{opt.label}</span>
                  </div>
                  <div className={`w-10 h-5 rounded-full relative transition-colors ${(options as any)[opt.id] ? 'bg-indigo-600' : 'bg-gray-300 dark:bg-gray-700'}`}>
                    <div className={`absolute top-1 w-3 h-3 bg-white rounded-full transition-all ${(options as any)[opt.id] ? 'left-6' : 'left-1'}`} />
                  </div>
                </button>
              ))}

              <label className="block">
                <span className="text-[10px] font-black uppercase tracking-widest text-indigo-600 mb-2 block">Custom 404 Path</span>
                <input 
                  type="text" value={options.customError404} onChange={(e) => setOptions({...options, customError404: e.target.value})}
                  className="w-full bg-gray-50 dark:bg-gray-800 border-none rounded-2xl py-4 px-6 outline-none focus:ring-2 focus:ring-indigo-500 font-bold"
                />
              </label>
            </div>
          </div>

          {/* Code Result */}
          <div className="bg-gray-900 rounded-[3rem] p-10 border border-gray-800 shadow-2xl space-y-6 relative overflow-hidden">
             <div className="absolute top-0 right-0 p-12 opacity-5 text-indigo-500 pointer-events-none">
                <Server size={200} />
             </div>
             <div className="flex items-center justify-between relative z-10">
                <h3 className="text-[10px] font-black uppercase tracking-widest text-indigo-400">Generated .htaccess</h3>
                <button 
                  onClick={() => navigator.clipboard.writeText(generatedConfig)}
                  className="p-3 bg-white/5 hover:bg-white/10 rounded-xl text-white transition-colors"
                >
                  <Copy size={18} />
                </button>
             </div>
             <pre className="relative z-10 w-full bg-black/50 p-8 rounded-2xl text-emerald-400 font-mono text-sm break-all whitespace-pre-wrap border border-white/5 h-[300px] overflow-y-auto">
               {generatedConfig}
             </pre>
          </div>
        </div>
      </div>
    </ToolLayout>
  );
}
